apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
commonLabels:
  app: sealed-secrets
resources:
- sealed-secrets-namespace.yaml
# remote resource file, fails !! i don't know why ? it seems that only remote kustomize works, followed https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#url-format
#- github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.4/controller.yaml
- controller.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: sealed-secrets-controller
  path: sc-patch.yaml
